version: '3.4'
services:
  db:
    image: postgres:14.10
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=Omar@012
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql  # تمكين الاتصال عبر Unix Socket

  odoo16:
    image: odoo:16
    user: root
    depends_on:
      - db
    ports:
      - "10019:8069"  # منفذ واجهة Odoo
      - "20014:8072"  # منفذ الدردشة الحية
    tty: true
    command: --
    environment:
      - HOST=/var/run/postgresql  # استخدام Unix Socket
      - USER=odoo
      - PASSWORD=odoo_password
      - DB_PORT=  # إزالة منفذ TCP لأننا نستخدم Unix Socket
      - DB_NAME=postgres
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - /var/run/postgresql:/var/run/postgresql  # الربط مع مجلد Unix Socket
    restart: always

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - 5051:5051
    restart: always
    depends_on:
      - db
    environment:
      DEFAULT_USER: mahmoud
      DEFAULT_PASSWORD: Omar012
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
