version: '3.4'
services:
  db:
    image: postgres:14.10
    user: root
    environment:
      - POSTGRES_USER=odoo   
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo16:
    image: odoo:16
    user: root
    depends_on:
      - db
    ports:
      - "10019:8069"
      - "20014:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
    volumes:
      #- /etc/timezone:/etc/timezone:trt
      #- /etc/localtime:/etc/localtime:trt
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - 5051:5051
    restart: always
    links:
      - db:db
    environment:
      DEFAULT_USER: mahmoud
      DEFAULT_PASSWORD: Omar012
     # VIRTUAL_HOST: 
     # LETSENCRYPT_HOST:
     # VIRTUAL_PORT: 5050
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      #- /var/run/docker.sock:/tmp/docker.sock
